# @no-log
GET http://localhost:8080/workouts

###
# @no-log
POST http://localhost:8080/workouts
Content-Type: application/json

{
  "title": "Second workout ever!"
}

###
# @no-log
POST http://localhost:8080/workouts/180855





############# SETS ####################################################
###
# @no-log
GET http://localhost:8080/workouts/181005/sets

###
# @no-log
POST http://localhost:8080/workouts/180855/sets
Content-Type: application/json

{
  "title": "Жим",
  "load": 80,
  "reps": 4,
  "index": 4,
  "rest": 120,
  "exerciseId": 5
}

###
# @no-log
PATCH  http://localhost:8080/sets/15
Content-Type: application/json

{
  "title": "Жим!",
  "load": 101100,
  "reps": 4,
  "index": 4,
  "rest": 120
}





############# EXERCISES ####################################################
###
# @no-log
GET http://localhost:8080/exercises

###
# @no-log
POST http://localhost:8080/exercises
Content-Type: application/json

{
  "title": "Жим штанги лёжа"
}

###
# @no-log
DELETE http://localhost:8080/exercises/2
Content-Type: application/json

{
  "title": "Жим штанги лёжа"
}

###
# @no-log
GET http://localhost:8080/exercises/3/sets
