name: Build the project
on:
  push:
    branches:
      - master
env:
  DOCKER_REGISTRY_URL: v1690117-images.cr.cloud.ru
  IMAGE_NAME: pnt-service
jobs:
  build-test:
    name: Publish Image And Update Service Deployment
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v3
      - name: Set up Docker buildx
        uses: https://github.com/docker/setup-buildx-action@v1
      - name: Log in to Evolution Artifact Registry
        uses: https://github.com/docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_KEY }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push docker image to Evolution Artifact Registry
        id: build_push
        uses: https://github.com/docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
          context: .
