spring:
  application:
    name: plan-n-track-service
  datasource:
    url: ${discovery.db-url}?currentSchema=${discovery.db-schema}
    username: ${discovery.db-user}
    password: ${discovery.db-pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: ${HOME_PAGE:http://localhost:8080}/login/oauth2/code/github
  flyway:
    url: ${discovery.db-url}
    user: ${discovery.db-user}
    password: ${discovery.db-pass}
    schemas: ${discovery.db-schema}
    enabled: true
    baseline-on-migrate: true

discovery:
  db-host: ${DB_HOST:localhost}:${DB_PORT:5432}
  db-name: ${DB_NAME:test}
  db-schema: ${DB_SCHEMA:workouts}
  db-user: ${DB_USER:postgres}
  db-pass: ${DB_PASS:0}

  db-url: jdbc:postgresql://${discovery.db-host}/${discovery.db-name}
